name: Quinta de Favaes
favicon: null
layout_spectrum: 0.4092484868597239
typography_spectrum: 0.7172718627844006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4888438945636153
  lightness: 0.8124471653718501
  saturation: 0.40902306139469147
  rhythmicContrast: 0.7070085918530822
purpose: []
