name: Quinta de Favaes
favicon: null
layout_spectrum: 0.74639
typography_spectrum: 0.64531
title: Quinta de Favaes - Turismo Rural
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef8c00'
    - '#efde9c'
    - '#7b7b8c'
    - '#733908'
    - '#290000'
  brandStrength: 0.5
  lightness: 0.8124471653718501
  saturation: 0.40902306139469147
  rhythmicContrast: 0.7070085918530822
purpose: []
